# Generated by Django 4.2.6 on 2023-11-27 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("multiple", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="details_csv",
            name="Department",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="details_csv",
            name="end_date",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="details_csv",
            name="grade",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="details_csv",
            name="sem",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="details_csv",
            name="start_date",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="details_csv",
            name="yr",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
