# Generated by Django 4.2.6 on 2023-11-28 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("multiple", "0002_details_csv_department_details_csv_end_date_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="civil_details",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("verify_id", models.CharField(blank=True, max_length=12)),
                ("name", models.CharField(blank=True, max_length=122)),
                ("yr", models.CharField(blank=True, max_length=200)),
                ("sem", models.CharField(blank=True, max_length=200)),
                ("grade", models.CharField(blank=True, max_length=200)),
                ("Department", models.CharField(blank=True, max_length=200)),
                ("start_date", models.CharField(blank=True, max_length=200)),
                ("end_date", models.CharField(blank=True, max_length=200)),
                ("program", models.CharField(blank=True, max_length=122)),
                ("year", models.CharField(blank=True, max_length=8)),
                ("tx_rc", models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="comp_details",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("verify_id", models.CharField(blank=True, max_length=12)),
                ("name", models.CharField(blank=True, max_length=122)),
                ("yr", models.CharField(blank=True, max_length=200)),
                ("sem", models.CharField(blank=True, max_length=200)),
                ("grade", models.CharField(blank=True, max_length=200)),
                ("Department", models.CharField(blank=True, max_length=200)),
                ("start_date", models.CharField(blank=True, max_length=200)),
                ("end_date", models.CharField(blank=True, max_length=200)),
                ("program", models.CharField(blank=True, max_length=122)),
                ("year", models.CharField(blank=True, max_length=8)),
                ("tx_rc", models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="elec_details",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("verify_id", models.CharField(blank=True, max_length=12)),
                ("name", models.CharField(blank=True, max_length=122)),
                ("yr", models.CharField(blank=True, max_length=200)),
                ("sem", models.CharField(blank=True, max_length=200)),
                ("grade", models.CharField(blank=True, max_length=200)),
                ("Department", models.CharField(blank=True, max_length=200)),
                ("start_date", models.CharField(blank=True, max_length=200)),
                ("end_date", models.CharField(blank=True, max_length=200)),
                ("program", models.CharField(blank=True, max_length=122)),
                ("year", models.CharField(blank=True, max_length=8)),
                ("tx_rc", models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="mech_details",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("verify_id", models.CharField(blank=True, max_length=12)),
                ("name", models.CharField(blank=True, max_length=122)),
                ("yr", models.CharField(blank=True, max_length=200)),
                ("sem", models.CharField(blank=True, max_length=200)),
                ("grade", models.CharField(blank=True, max_length=200)),
                ("Department", models.CharField(blank=True, max_length=200)),
                ("start_date", models.CharField(blank=True, max_length=200)),
                ("end_date", models.CharField(blank=True, max_length=200)),
                ("program", models.CharField(blank=True, max_length=122)),
                ("year", models.CharField(blank=True, max_length=8)),
                ("tx_rc", models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
