# Generated by Django 4.2.6 on 2023-11-27 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_remove_details_email_details_tx_rc_details_verify_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="details",
            name="Department",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="details",
            name="end_date",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="details",
            name="grade",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="details",
            name="sem",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="details",
            name="start_date",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="details",
            name="yr",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
